services:
  startup:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    container_name: startup
    ports:
      - "${NUXT_APP_PORT}:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=${NUXT_ENVIRONMENT}
